### ISSUE TITLE
Estudio e implementación del preprocesado de la imagen

### ISSUE THREAD

**Issue by magar22m** [uxin94/AIVA-Sistema-de-identificacion-automatica-de-crotales#2]
4 días.

Determinar las técnicas necesarias para obtener un preprocesado adecuado para la localización óptima de los números de los crotales.

**Comment by uxin94** [comment]
Hemos hecho un preprocesado, pero no completamente adaptativo para todas las imágenes. Hay que darle una vuelta.

**Comment by uxin94** [comment]
Tarea terminada. Tiempo dedicado: 2 días.

**Comment by uxin94** [comment]
Se ha modificado el preprocesamiento para optimizar la lectura de los números y disminuir los errores que comete el tesseract. Además es un código más eficiente y sencillo.

Tiempo dedicado: 3 días.
