### ISSUE TITLE
Implementación del algoritmo de localización

### ISSUE THREAD

**Issue by magar22m** [uxin94/AIVA-Sistema-de-identificacion-automatica-de-crotales#3]
3 días.

Localización de la zona de la imagen donde se encuentran los números a identificar

**Comment by uxin94** [comment]
Según cómo se haya preprocesado la imagen la localización funciona mejor o peor. Los bounding boxes se adaptan perfectamente a cada cifra.

**Comment by uxin94** [comment]
Tarea terminada. Tiempo empleado: 2 días.
