### ISSUE TITLE
Implentación del algoritmo de identificación.

### ISSUE THREAD

**Issue by magar22m** [uxin94/AIVA-Sistema-de-identificacion-automatica-de-crotales#4]
4 días.

Emplear un OCR capaz de identificar los números que aparecen en la imagen.

**Comment by uxin94** [comment]
Hay problemas con el OCR ya que en algunas imágenes identifica letras en vez de números.

**Comment by magar22m** [comment]
Además de mejorar los parámetros de la configuración del OCR se ha añadido un diccionario para reducir errores.

Tiempo empleado: 4 días.
