### ISSUE TITLE
Documentación del Diseño de la solución.

### ISSUE THREAD

**Issue by uxin94** [uxin94/AIVA-Sistema-de-identificacion-automatica-de-crotales#6]
- Introducción al desarrollo realizado.
- Descripción del funcionamiento de los test.
- Diagrama UML estático de clases con las clases desarrolladas.
- Explicación de las clases y sus métodos.
- Diagrama UML de secuencia con un ejemplo de uso de la aplicación.
- Diagrama UML de actividad para cada algoritmo.

Tiempo estimado: 1 día.

**Comment by magar22m** [comment]
Tiempo empleado: 1 día.
